# Generated by Django 5.0.7 on 2024-07-21 05:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_url', models.URLField()),
                ('url_hash', models.CharField(max_length=8, unique=True)),
                ('hits', models.PositiveIntegerField(help_text='Track the number of hits on this URL')),
                ('last_hit', models.DateTimeField(null=True)),
            ],
        ),
    ]
